baseURL = 'http://federama.dev/'
languageCode = 'en-us'
title = 'Federico Ramacciotti'
theme = 'cactus'

# Main menu which appears below site header.
[[menu.main]]
name = "./home"
url = "/"
weight = 1

[[menu.main]]
name = "./about_me"
url = "/about"
weight = 2

[[menu.main]]
name = "./blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "./tags"
url = "/tags"
weight = 4

[params]

colortheme = "dark" # dark, light, white, or classic
rss = true          # generate rss feed. default value is false
# googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = false # default

# Home page settings
description = """
  Hey ðŸ‘‹, I'm Federico Ramacciotti, a 25-year-old software engineer working at [Satispay](https://www.satispay.com/it-it/).
  I got a Master's Degree in 2024 in Computer Science at the University of Pisa.

  I love to learn new technologies and I believe in learning-by-doing, so I built a lot of small tools to practice with the languages; you can find them all on my [github profile](https://github.com/0xfederama).

  Subscribe to my [RSS feed](/posts/index.ml) to get updates on new posts!
  """
mainSection = "posts" # your main section
tocInline = true
showAllPostsOnHomePage = false # default
postsOnHomePage = 3 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = false # show tags overview by default.
showProjectsList = true # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/0xfederama" # title link for projects list

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default

# Post page settings
show_updated = true # default
showReadTime = true # default

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/0xfederama"
[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/federico-ramacciotti"
#  [[params.social]]
#    name = "twitter"
#    link = "https://twitter.com/vgfede"
#  [[params.social]]
#    name = "mastodon"
#    link = "https://techhub.social/@fede"
[[params.social]]
name = "email"
link = "vgfede@gmail.com" # no need for "mailto:" in the head
